name: 🔴 Stop Parkalot

on:
  # daily at 12:02 UTC → 13:02 BST
  schedule:
    - cron: '2 12 * * *'
  # allow manual runs from the Actions UI or via `gh workflow run`
  workflow_dispatch:

jobs:
  stop-container:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Stop (delete) container
        run: |
          az container delete \
            --resource-group parkalot-rg \
            --name parkalot-cron \
            --yes
